// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "src/prisma/schema.prisma",
    migrations: {
        path: "src/prisma/migrations",
        seed: "ts-node -r tsconfig-paths/register src/prisma/seed.ts",
    },
    datasource: {
        url: process.env["DATABASE_URL"],
        // Only `prisma migrate diff --from-migrations` needs this: it replays the
        // migration history into a throwaway database to compute the diff, so
        // never point it at the real one.
        shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
    },
});
